//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ButtonExit {
            get {
                object obj = ResourceManager.GetObject("ButtonExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonFullScreen {
            get {
                object obj = ResourceManager.GetObject("ButtonFullScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMuteOff {
            get {
                object obj = ResourceManager.GetObject("ButtonMuteOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMuteOn {
            get {
                object obj = ResourceManager.GetObject("ButtonMuteOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonPause {
            get {
                object obj = ResourceManager.GetObject("ButtonPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonPlay {
            get {
                object obj = ResourceManager.GetObject("ButtonPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonSmallScreen {
            get {
                object obj = ResourceManager.GetObject("ButtonSmallScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonSound {
            get {
                object obj = ResourceManager.GetObject("ButtonSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonStop {
            get {
                object obj = ResourceManager.GetObject("ButtonStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownCommandBorder {
            get {
                object obj = ResourceManager.GetObject("DownCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownSoundBorder {
            get {
                object obj = ResourceManager.GetObject("DownSoundBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftCommandBorder {
            get {
                object obj = ResourceManager.GetObject("LeftCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDownCommandBorder {
            get {
                object obj = ResourceManager.GetObject("LeftDownCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftDownSoundBorder {
            get {
                object obj = ResourceManager.GetObject("LeftDownSoundBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftScreenBorder {
            get {
                object obj = ResourceManager.GetObject("LeftScreenBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftUpCommandBorder {
            get {
                object obj = ResourceManager.GetObject("LeftUpCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftUpScreenBorder {
            get {
                object obj = ResourceManager.GetObject("LeftUpScreenBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preloader128 {
            get {
                object obj = ResourceManager.GetObject("Preloader128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preloader192 {
            get {
                object obj = ResourceManager.GetObject("Preloader192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preloader32 {
            get {
                object obj = ResourceManager.GetObject("Preloader32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preloader64 {
            get {
                object obj = ResourceManager.GetObject("Preloader64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightCommandBorder {
            get {
                object obj = ResourceManager.GetObject("RightCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDownCommandBorder {
            get {
                object obj = ResourceManager.GetObject("RightDownCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightDownSoundBorder {
            get {
                object obj = ResourceManager.GetObject("RightDownSoundBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightScreenBorder {
            get {
                object obj = ResourceManager.GetObject("RightScreenBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightUpCommandBorder {
            get {
                object obj = ResourceManager.GetObject("RightUpCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightUpScreenBorder {
            get {
                object obj = ResourceManager.GetObject("RightUpScreenBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackbarDownBorder {
            get {
                object obj = ResourceManager.GetObject("TrackbarDownBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackbarHorizontal {
            get {
                object obj = ResourceManager.GetObject("TrackbarHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackbarLeftBorder {
            get {
                object obj = ResourceManager.GetObject("TrackbarLeftBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackbarRightBorder {
            get {
                object obj = ResourceManager.GetObject("TrackbarRightBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackbarUpBorder {
            get {
                object obj = ResourceManager.GetObject("TrackbarUpBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackbarVertical {
            get {
                object obj = ResourceManager.GetObject("TrackbarVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackThumbHorizontal {
            get {
                object obj = ResourceManager.GetObject("TrackThumbHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrackThumbVertical {
            get {
                object obj = ResourceManager.GetObject("TrackThumbVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpCommandBorder {
            get {
                object obj = ResourceManager.GetObject("UpCommandBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpScreenBorder {
            get {
                object obj = ResourceManager.GetObject("UpScreenBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
